# First Observations {#overview}

The `bookdown` package and [book](https://bookdown.org/yihui/bookdown/get-started.html) is definitely the best way to get started. However, in practice I always find myself copying an existing, working book and modifying it instead of starting from scratch. So this tutorial is going to have you do that as well, using this book as the one you copy from.

[more setup here]

You will have to name your book's repository. To differentiate your book's repo name from this "bookdown-tutorial" repo, here we'll call your book "awesome-book" *but you should consistently name it what you want to name it*.

**Get "bookdown-tutorial" on your local computer**

1. Go to <https://github.com/jules32/bookdown-tutorial>
1. Click the green "clone or download" button and DOWNLOAD ZIP. 
1. Locally on your computer, unzip the folder, save it in a reasonable place
1. Rename 2 things from "bookdown-tutorial" to "awesome-book". You can do this in the finder/windows explorer:
  - the folder itself (that you just unzipped)
  - the .Rproj file
1. Double-click the .Rproj file to launch RStudio 

**Create your "awesome-book" GitHub repo**

1. Go to your GitHub account: github.com/username
1. Click on Repositories, and the green button "New" to create a new repo
1. Name this new repo "awesome-book"
1. Check to initialize this repo with a README
1. Click the green "create repository" button — this will take you to your new repo
1. Click the green "clone or download" button and COPY URL

**Turn "bookdown-tutorial" into "awesome-book"**

1. In RStudio




